dist: trusty
language: java
jdk:
  - oraclejdk8
script:
  - chmod -R ug+x .travis
  - .travis/build.sh
notifications:
  webhooks: https://simona.ie3.e-technik.tu-dortmund.de/chat/hooks/RtG988s8R4iY3vM32/6JNKKYCwq9DYbqWgkFBmmdzRiAHvXAgLQeNyWNKnfWyjvHR3
after_success:
      - bash <(curl -s https://codecov.io/bash)
