dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
script:
  - chmod -R ug+x .travis
  - .travis/eccodes.sh
  - .travis/build.sh
notifications:
  webhooks: https://simona.ie3.e-technik.tu-dortmund.de/chat/hooks/RtG988s8R4iY3vM32/6JNKKYCwq9DYbqWgkFBmmdzRiAHvXAgLQeNyWNKnfWyjvHR3
after_success:
      - bash <(curl -s https://codecov.io/bash)
